# https://github.com/Homebrew/homebrew-cask-fonts
tap "homebrew/cask-fonts"

# https://github.com/Homebrew/homebrew-cask-versions
tap "homebrew/cask-versions"

# https://github.com/buo/homebrew-cask-upgrade
tap "buo/cask-upgrade"

brew "font-inconsolata"
brew "font-inconsolata-nerd-font"
brew "font-inconsolata-go-nerd-font"
brew "font-fira-code"

# https://github.com/BurntSushi/ripgrep
brew "ripgrep"

# https://github.com/ajeetdsouza/zoxide
brew "zoxide"

# https://github.com/junegunn/fzf
brew "fzf"

# https://github.com/github/hub
brew hub

# https://github.com/neovim/neovim
brew neovim

# https://github.com/dandavison/delta
brew git-delta

# https://formulae.brew.sh/cask/google-chrome
cask "google-chrome"
cask "google-chrome-canary"

# https://formulae.brew.sh/cask/slack
cask "slack"

# https://formulae.brew.sh/cask/spotify
cask "spotify"

# https://formulae.brew.sh/cask/raycast
cask "raycast"

cask "visual-studio-code-insiders"

# https://formulae.brew.sh/cask/iterm2
cask "iterm2"
